### PR TITLE
Add configurable lock/unlock animations & prop support

### PR DESCRIPTION
**Pull request by citRaTTV**
**Describe Pull request**
Add configurable lock/unlock animation w/ prop support. New configuration parameters:
```lua
-- Vehicle lock settings
Config.LockToggleAnimation = {
    AnimDict = 'anim@mp_player_intmenu@key_fob@',
    Anim = 'fob_click',
    Prop = 'prop_cuff_keys_01',
    PropBone = 57005,
    WaitTime = 500,
}
Config.LockAnimSound = "keys"
Config.LockToggleSound = "lock"
Config.LockToggleDist = 8.0
```

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

### CODE REVIEW

**Comment by adtgamer** [comment]
I just don't understand where to put this code

**Comment by citRaTTV** [comment]
> I just don't understand where to put this code

If it gets merged into the resource, you'll just have to update it :)

**Comment by adtgamer** [comment]
you don't send me what you edited/?

**Comment by citRaTTV** [comment]
> you don't send me what you edited/?

It's all shown here in the Files changed tab https://github.com/qbcore-framework/qb-vehiclekeys/pull/242/files

**Comment by adtgamer** [comment]
I edited it but there was an error, you can't send it to me, it's already edited

**Comment by citRaTTV** [comment]
> I edited it but there was an error, you can't send it to me, it's already edited

You can download the files directly here https://github.com/citRaTTV/qb-vehiclekeys/tree/feat%2Flock-anim-config

**Comment by adtgamer** [comment]
erro 
image

**Comment by adtgamer** [comment]
> > I edited it but there was an error, you can't send it to me, it's already edited
> 
> You can download the files directly here https://github.com/citRaTTV/qb-vehiclekeys/tree/feat%2Flock-anim-config

THANCKS  perfect

**Pull request merged**
