### PR TITLE
fix(client/server): Add player vehicle check for parked cars. Fixes #156

### LINKED ISSUE #156: [BUG] Config.LockNPCParkedCars = true - causes player cars to become locked when they get out without locking
**Describe the bug**
When this setting is true, if a player gets out of their car and does not lock it another player cannot get in the car even if the door is open, this is still true if the player that owns the car unlocks it another player will still not be able to get in the drivers seat.

**To Reproduce**
1. Get out of owned car without locking
2. Let player try to get in and drive.
3. It will seem like the door is locked with the animation even if the owner unlocks it.

**Expected behavior**
Car should remain unlocked if the owner or key holder did not lock.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tom-osborne**
**Describe Pull request**
This PR adds a callback to check if the vehicle the player is attempting to enter is owned by a player. This is to address the issue of player vehicles unintentionally becoming locked after the owner leaves the vehicle. The NPC vehicle check logic did not cater for a player owned vehicle and treated any empty vehicle as an NPC vehicle, so when the config option `Config.LockNPCParkedCars` was set to `true` this would lock that vehicle when a player without keys tried to enter the empty vehicle.

Fixes #156, #159, #172 & #178

As with my previous PR attempting to fix this, this also needs testing. The following scenarios should be tested with `Config.LockNPCParkedCars = true`:  

**Scenario 1**  
1. Owner gets out of vehicle while vehicle is unlocked.
2. Other player without keys attempts to get in the vehicle.  

**Expected result**: Both players should be able to enter the unlocked vehicle.

**Scenario 2**  
1. Owner locks vehicle from outside
2. Other player tries to enter. 

**Expected result**: Vehicle should be locked.

**Scenario 3**
1. Owner unlocks vehicle. 
2. Other player tries to enter empty vehicle.

**Expected result**: Vehicle should be unlocked

**Other tests**
- [x] Lockpicking should remain as it was. (able to enter a vehicle NPC or owned after lock pick success)
- [x] Config options for NPC cars should work as intended.
- [x] Alternative config options should not affect Scenario's 1, 2 & 3

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by CptNoHand** [comment]
For me player cars are unlocked and npc cars are locked as they should be

**Comment by tom-osborne** [comment]
https://github.com/qbcore-framework/qb-vehiclekeys/issues/156#issuecomment-1242404348_

**Comment by bluecraank** [comment]
Working good, but now if player locks veh from outside, its still open for other people

**Comment by tom-osborne** [comment]
@bluecraank Shouldn't be. I can't replicate this. Can you make sure you don't have any conflicting resource that may be locking/unlocking at the same time?

**Comment by bluecraank** [comment]
@tom-osborne We can verify that if the player without keys is next to the car and the owner is locking the car, he can still get inside the car. if the player is far away (~5-8) and the owner locks, that it works as expected.

We have no other locking system but it is a Custom car.

**Comment by tom-osborne** [comment]
@bluecraank Okay I have replicated this now. It only seems to happen if the other player gets in and then out. The owner then locks the car, but for the other player it appears unlocked.

I will investigate now. Thanks for the feedback

**Comment by bluecraank** [comment]
Yes, same scenario tested

**Comment by Raizennnn** [comment]
Hi there, is the locking from outside fixed yet?

**Comment by tom-osborne** [comment]
@Raizennnn not yet. I was investigating last night. It is something to do with entity ownership, but not got a solution yet.

**Comment by bluecraank** [comment]
Something new?

**Comment by CptNoHand** [comment]
If the person is with me in the car and we get out and I lock it, he can get in again. But when i lock it twice, it locks and works, but i have to lock it twice. I even get the lock message twice instead of it saying unlocked the second time.

**Comment by tom-osborne** [comment]
> If the person is with me in the car and we get out and I lock it, he can get in again. But when i lock it twice, it locks and works, but i have to lock it twice. I even get the lock message twice instead of it saying unlocked the second time. 
> 
> Edit: I just had the same but the other way around and had to unlock twice so he can enter.

Yeah thats a known issue and seems to be related to entity ownership, working on a fix.

**Comment by tom-osborne** [comment]
@CptNoHand @bluecraank @Raizennnn Please test now. I think this is now resolved.

**Comment by CptNoHand** [comment]
Just tested this and it works

One thing im not sure if its intended, cause it would be realistic. 
If both are out of the car and i open it and someone gets in, when hes in and i lock it and he gets out its unlocked. which is realistic, but i tested every situation, so just wanted to tell.

**Comment by tom-osborne** [comment]
Thanks. Yeah if a player is inside while it's locked they can get out. Not realistic but locking people in cars would be undesirable I think.

**Comment by tom-osborne** [comment]
@CptNoHand did you test it on server with multiple players? (More than 2 people)

**Comment by bluecraank** [comment]
Works fine! And great "not wanted" feature that players in car cannot be locked

**Comment by CptNoHand** [comment]
> @CptNoHand did you test it on server with multiple players? (More than 2 people)

Yes, we tested it with 4 players.

**Comment by CptNoHand** [comment]
> Works fine! And great "not wanted" feature that players in car cannot be locked

I don't want that at all aswell, don't get me wrong. I like it realistic.

**Comment by Raizennnn** [comment]
so i just tested this, seems like its working but sometimes npc car locks dont work and when you aim on them there isnt any event to carjack cars, and when you lockpick a door there is no hotwiring, you can drive the car but you do need to lockpick it to get the keys in order to lock the car

**Comment by tom-osborne** [comment]
@Raizennnn What do you mean "sometimes npc car locks dont work" - can you elaborate?

Carjacking can be done by using a lockpick or advanced lockpick while standing next to the vehicle, no need to target the vehicle.

**Comment by Raizennnn** [comment]
@tom-osborne sometimes the lock on npc cars wont work, i need to restart the resource in order to make the npc doors lock

**Comment by Raizennnn** [comment]
any news?

**Comment by SirOMGitsYOU** [comment]
> @CptNoHand @bluecraank @Raizennnn Please test now. I think this is now resolved.

i seem to be still experiencing this issue downloaded the latest build from your GitHub if the person is in the vehicle before locking the car and we get out and I lock it then he can freely enter the vehicle and it doesn’t seem to actually “lock” once this happens then have to go spamming L to get it to lock then unlock and it doesn’t really turn back to normal functionality

**Comment by SirOMGitsYOU** [comment]
Noticed people also get glued and permanently stuck occasionally in the vehicle and then removing the vehicle or tping out just then affects the next vehicle you get in

**Comment by CptCoggs** [comment]
This issue SirOMGitsYOU has mentioned is the same issue I mentioned in #172

**Comment by tom-osborne** [comment]
@CptCoggs Can you explain the steps to replicate the issue? Not sure I follow it exactly?

**Comment by SirOMGitsYOU** [comment]
> @CptCoggs Can you explain the steps to replicate the issue? Not sure I follow it exactly?

Sadly we haven't been able to figure out how to replicate it, Not sure if it's tied to how long people are in the server but one thing we noticed is it does mainly occur after long play sessions

**Comment by Millusion** [comment]
any update on this?

**Comment by tom-osborne** [comment]
> any update on this?

On what exactly?

**Comment by Millusion** [comment]
> 

If it can be merged in (and used), if you need some help testing it, i'm up for it.

**Comment by tom-osborne** [comment]
> > 
> 
> If it can be merged in (and used), if you need some help testing it, i'm up for it.

Yeah test it please.

**Comment by Millusion** [comment]
> > > 
> > 
> > 
> > If it can be merged in (and used), if you need some help testing it, i'm up for it.
> 
> Yeah test it please.

the only issue i found directly was following scenario:

- get into playerowned car
- lock car from inside
- exit car is still possible
- entry to car is prohibited

**Comment by tom-osborne** [comment]
> > > > 
> > > 
> > > 
> > > If it can be merged in (and used), if you need some help testing it, i'm up for it.
> > 
> > 
> > Yeah test it please.
> 
> the only issue i found directly was following scenario:
> 
>     * get into playerowned car
> 
>     * lock car from inside
> 
>     * exit car is still possible
> 
>     * entry to car is prohibited
> 
> 
> but like i read up top this is more a feature then a bug. So for me this patch works fine. I'm merging it in our live server now.

Thanks for testing. This is standard GTA behaviour. Players can't be locked in vehicles.

**Review by Millusion — APPROVED** [review]

**Comment by brynnie1** [comment]
Sorry I used this above but getting this error 
image

This is in relation to get vehicle keys

**Comment by tom-osborne** [comment]
> Sorry I used this above but getting this error image
> 
> This is in relation to get vehicle keys i'm stood right infront of the car and trying to lock it it makes the sound and the animation of locking, but then continues to do teh animation and doesn't lock the vehicle.

And what is `server/main.lua: line 53` for you?

**Comment by Millusion** [comment]
@tom-osborne Update from my side: been using this on our live server for the past 2 weeks with around 15-20 people online and no issues to report about this.

**Comment by tom-osborne** [comment]
> @tom-osborne Update from my side: been using this on our live server for the past 2 weeks with around 15-20 people online and no issues to report about this.

Thank you

**Pull request merged**
