### PR TITLE
prevent notify or function spam

### PR DESCRIPTION
**Pull request by Enzo-DC**
for people that have qs-smartphone and call valet, they have a spam of notify ^^

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by Re1ease** [comment]
Can you give me more information about why and how it spams when using qs-smartphone and 'call valet'?
I can't see why it would spam, and I don't have either resource, so I can't replicate it.

**Comment by Enzo-DC** [comment]
I don't know why he does this notification spam, but I know that whoever uses this phone has this problem. the phone is protected by fivem escrow, so you can't see the code.

unknown

**Comment by Re1ease** [comment]
Have you personally loaded this code into an updated qbcore project and checked all it's functionality?

**Comment by Enzo-DC** [comment]
yes ofc

**Comment by tom-osborne** [comment]
@Enzo-DC so it only happens when you install qs-smartphone?

**Comment by Enzo-DC** [comment]
yes, only after installing qs-smartphone .. they say it's a problem of qb-vehiclekeys, but i doubt it, they will have this event in the thread with while true of the valet and it repeats until it finishes... in Italy we say "extreme bitters, extreme remedies"

**Comment by tom-osborne** [comment]
> yes, only after installing qs-smartphone .. they say it's a problem of qb-vehiclekeys, but i doubt it, they will have this event in the thread with while true of the valet and it repeats until it finishes... in Italy we say "extreme bitters, extreme remedies"

@Enzo-DC  Yeah, I agree it is a problem with qs-smartphone. We typically check whether the player has keys before we run this event, so I do not want to add another check within the event just to fix this issue as it will duplicate the check for no reason. 

For that reason I will close this without merging, but obviously you can keep it in your code as a temporary fix. Let's hope qs-smartphone get fixed instead. 

Thanks for your contribution regardless.

**Pull request closed without merging**
