### PR TITLE
Feature: ItsANoBrainer rewrite

### PR DESCRIPTION
**Pull request by IdrisDose**
Changes stated in #80

### CODE REVIEW

**Comment by ItsANoBrainer** [comment]
Refactored the entire resource because the key system was not working.

No longer does a server callback 10 or so times a second, on top of other bad practices.

Tested pretty much everything with my devs, but there might be some weird issues we havnt found. Please lookover as I've been going crazy with the small tedious issues I've come across doing this.

Throwing this up to get feedback, and for people to use who want it.

Features:

Keys are saved server side, and sent to each client when they are added or removed, as well as on character selection. This allows characters to leave and come back in the same server uptime session and still have the same keys
Keys are only pulled from the server once on character load
Giving keys has 3 types, /givekeys with an id will attempt to give keys you have to an id, not including an id will try to give it to the closest person, and if you're in a vehicle it will give to everyone
Can only give keys to vehicles you have keys to
Server event to force acquire keys to a plate for a person (for lockpicking/stealing/spawning, etc.)
Can Carjack an NPC with a gun, has different percentages to work based on weapon (config)
Take keys from dead npc drivers
Can lockpick a car to unlock the doors
Can hotwire a car if you're in the driver seat of the vehicle you dont have keys to to get keys
Keeps the engine of a vehicle off if you dont have keys to it (allows other resources to attempt to toggle car engine without needing to interface if you have keys or not)
Vehicle blacklist system for vehicles you dont want to be lockable (always unlocked)
Police Alerts from lockpicking/hotwiring/carjacking
Export to check if you have keys to a vehicle
Locking/unlocking with hotkey
Locking/unlocking and giving keys uses a custom GetVehicleInDirection you are facing for realism/accuracy
Fully compatible with old resource. Has an event handler for 'vehiclekeys:client:SetOwner' in which it gives keys for that plate
Some other shit I probably forgot
TODO:

Add LOCALE support
Stop peds from wanting to get back into the vehicle they just got carjacked out of as they're fleeing

**Comment by menkzy** [comment]
Missing `Config.NoLockVehicles = { }` in the config, throws `SCRIPT ERROR: @qb-vehiclekeys/client/main.lua:99: bad argument #1 to 'for iterator' (table expected, got nil)`

**Comment by xenfovn** [comment]
It will be more realistic if you give the key to someone else and you have that key deleted, avoiding duplicates

**Comment by Andyauk** [comment]
> Missing `Config.NoLockVehicles = { }` in the config, throws `SCRIPT ERROR: @qb-vehiclekeys/client/main.lua:99: bad argument #1 to 'for iterator' (table expected, got nil)`

i noticed this too, was about to post, when I noticed you had.

**Comment by milotiro95** [comment]
Config.NoLockVehicles = { } solve the first issue but when trying to steal a car with a gun I have this issues now (look 

picture)

**Comment by Andyauk** [comment]
> Config.NoLockVehicles = { } solve the first issue but when trying to steal a car with a gun I have this issues now (look  picture)

I'm going to try this out myself in a few hours, as it's one thing I forgot to check.

**Pull request closed without merging**
