### PR TITLE
['FIX']: Console error : attempt to index a nil value

### PR DESCRIPTION
**Pull request by AnishBplayz**
> [script:qb-vehiclekey] SCRIPT ERROR: @qb-vehiclekeys/server/main.lua:53: attempt to index a nil value 
> [script:qb-vehiclekey] > TriggerCallback (@qb-core/server/functions.lua:251) 
> [script:qb-vehiclekey] > handler (@qb-core/server/events.lua:152)
> [      script:qb-core] SCRIPT ERROR: error object is not a string

**Line 53 attempt to index a nil value fixed**

`Tested and fixed :)`

Any suggestions are appreciated....

### CODE REVIEW

**Comment by Shocksua** [comment]
Error loading script server/main.lua in resource qb-vehiclekeys: @qb-vehiclekeys/server/main.lua:103: attempt to index a nil value (global 'Lang')

**Comment by AnishBplayz** [comment]
Do you have the latest core ?

If yes then redownload the qb-vehiclekeys completely

**Comment by Shocksua** [comment]
> Tienes el ultimo core?
> 
> En caso afirmativo, vuelva a descargar qb-vehiclekeys por completo

If I download a complete FX base 0 it works perfectly. But if I download the qb.core that you indicate and replace it with qb.core that I have in my server, the palyer remains in the loading screen. I appreciate your answer.

**Comment by ChristianBDev** [comment]
The previous code works fine for me, @Shocksua if your problem still persists then you need to get with one of us or make a thread in the fivem-support channel within the QBCore discord. The PR is irrelevant and does the same thing as the previous line of code.

**Review by zwkf — APPROVED** [review]
LGTM

**Comment by ChristianBDev** [comment]
LGTM

**Pull request merged**
