### PR TITLE
Make config work.

### PR DESCRIPTION
**Pull request by Jamie9192**
Config.UseKeyFob, was round the wrong way. 🤦

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by TehGuardian** [comment]
Tested and good to go.

**Review by TehGuardian — APPROVED** [review]
Tested and Working

**Comment by ChristianBDev** [comment]
LGTM

**Review by zwkf — APPROVED** [review]
LGTM

**Pull request merged**
